services:

  # ---------------------------------------------------------
  # EarnBox Dashboard (Frontend)
  # ---------------------------------------------------------
  earnbox:
    build: ./dashboard
    container_name: earnbox
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - earning_net

  # ---------------------------------------------------------
  # EarnBox Backend (API)
  # ---------------------------------------------------------
  backend:
    user: root
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - earning_net

  # ---------------------------------------------------------
  # Honeygain
  # ---------------------------------------------------------
  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    restart: unless-stopped
    command: >
      -tou-accept
      -email ${HONEYGAIN_EMAIL}
      -pass ${HONEYGAIN_PASSWORD}
      -device ${HONEYGAIN_DEVICE}
    environment:
      - TZ=${TZ}
    networks:
      - earning_net

  # ---------------------------------------------------------
  # Pawns
  # ---------------------------------------------------------
  pawns:
    image: iproyal/pawns-cli:latest
    container_name: pawns
    restart: unless-stopped
    command: >
      --email=${PAWNS_EMAIL}
      --password=${PAWNS_PASSWORD}
      --device-name=${PAWNS_DEVICE}
      --accept-tos
    environment:
      - TZ=${TZ}
    networks:
      - earning_net

  # ---------------------------------------------------------
  # Netdata (System Stats)
  # ---------------------------------------------------------
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    restart: unless-stopped
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /sys/class/thermal:/sys/class/thermal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - earning_net

  # ---------------------------------------------------------
  # Dozzle (Container Logs)
  # ---------------------------------------------------------
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - earning_net

networks:
  earning_net:
    driver: bridge
