version: '3.8'

services:

  earnapp:
    image: earnapp/earnapp:latest
    container_name: earnapp
    restart: always
    environment:
      - EARNAPP_DEVICE_TOKEN=${EARNAPP_TOKEN}
    volumes:
      - earnapp_data:/data

  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    restart: always
    command: >
      -tou-accept
      -email ${HONEYGAIN_EMAIL}
      -pass ${HONEYGAIN_PASSWORD}
      -device ${HONEYGAIN_DEVICE}

  pawns:
    image: iproyal/pawns-cli:latest
    container_name: pawns
    restart: always
    command: >
      -email=${PAWNS_EMAIL}
      -password=${PAWNS_PASSWORD}
      -device-name=${PAWNS_DEVICE}

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --cleanup
      --include-restarting
      --include-stopped
      --revive-stopped
      --schedule ${WATCHTOWER_SCHEDULE}
  
  pi-monitor:
    image: carlosedp/rpi-monitoring
    container_name: pi-monitor
    restart: always
    privileged: true
    ports:
      - "8888:8888"
volumes:
  earnapp_data:
